#!/usr/bin/bash

INPUT=$1
TMPFILE=/tmp/$$

gzip -cd "$INPUT" | sed '/^"trace"/Q' | tr -d '\n' | sed -r -e 's/,$/}\n/' > ${TMPFILE}.meta.jsonl
gzip -cd "$INPUT" | grep '^\[' | sed -r -e 's/ ]$/,/' > ${TMPFILE}.data.jsonl

clickhouse-local --query "
    INSERT INTO FUNCTION remoteSecure('kvzqttvc2n.eu-west-1.aws.clickhouse-staging.com', default.planes_mercator, 'default', '')
    SELECT
        CAST(timestamp + time_offset AS DateTime64(3)) AS time, time::Date AS date,
        icao, r, t, dbFlags, noRegData, ownOp, year, desc,
        lat, lon,
        toInt32OrZero(altitude),
        ground_speed,
        track_degrees,
        flags,
        vertical_rate,
        aircraft.alert,
        aircraft.alt_geom,
        aircraft.gva,
        aircraft.nac_p,
        aircraft.nac_v,
        aircraft.nic,
        aircraft.nic_baro,
        aircraft.rc,
        aircraft.sda,
        aircraft.sil,
        aircraft.sil_type,
        aircraft.spi,
        aircraft.track,
        aircraft.type,
        aircraft.version,
        aircraft.category,
        aircraft.emergency,
        aircraft.flight,
        aircraft.squawk,
        aircraft.baro_rate,
        aircraft.nav_altitude_fms,
        aircraft.nav_altitude_mcp,
        aircraft.nav_modes,
        aircraft.nav_qnh,
        aircraft.geom_rate,
        aircraft.ias,
        aircraft.mach,
        aircraft.mag_heading,
        aircraft.oat,
        aircraft.roll,
        aircraft.tas,
        aircraft.tat,
        aircraft.true_heading,
        aircraft.wd,
        aircraft.ws,
        aircraft.track_rate,
        aircraft.nav_heading,
        source,
        geometric_altitude,
        geometric_vertical_rate,
        indicated_airspeed,
        roll_angle
    FROM
        file('${TMPFILE}.data.jsonl', JSONCompactEachRow, '
            time_offset Decimal64(3),
            lat Float64,
            lon Float64,
            altitude String,
            ground_speed Float32,
            track_degrees Float32,
            flags UInt32,
            vertical_rate Int32,
            aircraft Tuple(
                alert            Int64,
                alt_geom         Int64,
                gva              Int64,
                nac_p            Int64,
                nac_v            Int64,
                nic              Int64,
                nic_baro         Int64,
                rc               Int64,
                sda              Int64,
                sil              Int64,
                sil_type         String,
                spi              Int64,
                track            Float64,
                type             String,
                version          Int64,
                category         String,
                emergency        String,
                flight           String,
                squawk           String,
                baro_rate        Int64,
                nav_altitude_fms Int64,
                nav_altitude_mcp Int64,
                nav_modes        Array(String),
                nav_qnh          Float64,
                geom_rate        Int64,
                ias              Int64,
                mach             Float64,
                mag_heading      Float64,
                oat              Int64,
                roll             Float64,
                tas              Int64,
                tat              Int64,
                true_heading     Float64,
                wd               Int64,
                ws               Int64,
                track_rate       Float64,
                nav_heading      Float64
            ),
            source LowCardinality(String),
            geometric_altitude Int32,
            geometric_vertical_rate Int32,
            indicated_airspeed Int32,
            roll_angle Float32
            /* , hex String */
        ') AS d,
        file('${TMPFILE}.meta.jsonl', JSONEachRow, '
            icao String,
            r String,
            t String,
            dbFlags Int32,
            noRegData Bool,
            ownOp String,
            year UInt16,
            timestamp Decimal64(3),
            desc String
        ') AS m
" || exit 1

rm ${TMPFILE}.{meta,data}.jsonl
